# Generated by Django 4.2.14 on 2024-08-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoltMan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolt_geometry',
            name='head_height',
            field=models.PositiveIntegerField(default=0, verbose_name='Head height:'),
        ),
        migrations.AlterField(
            model_name='bolt_geometry',
            name='headdiameter',
            field=models.FloatField(default=0, verbose_name='Head dieamter:'),
        ),
        migrations.AlterField(
            model_name='bolt_geometry',
            name='shank_length',
            field=models.PositiveIntegerField(default=0, verbose_name='Shank length:'),
        ),
        migrations.AlterField(
            model_name='bolt_geometry',
            name='thread_metric',
            field=models.BooleanField(default=0, verbose_name='Thread is metric:'),
        ),
        migrations.AlterField(
            model_name='bolt_geometry',
            name='thread_right_hand',
            field=models.BooleanField(default=0, verbose_name='Thread is right hand:'),
        ),
        migrations.AlterField(
            model_name='bolt_geometry',
            name='thread_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Thread size:'),
        ),
        migrations.AlterField(
            model_name='bolt_geometry',
            name='total_length',
            field=models.PositiveIntegerField(default=0, verbose_name='Total length:'),
        ),
        migrations.AlterField(
            model_name='bolt_geometry',
            name='tsa',
            field=models.FloatField(default=0, verbose_name='Tensile Stress Area (mm^2)'),
        ),
    ]
