# Generated by Django 4.2.14 on 2024-08-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoltMan', '0002_alter_bolt_geometry_head_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolt_geometry',
            name='material',
            field=models.ForeignKey(default=None, help_text='Select a geometry', null=True, on_delete=django.db.models.deletion.CASCADE, to='BoltMan.bolt_material'),
        ),
    ]
