# Generated by Django 4.2.14 on 2024-08-27 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoltMan', '0004_alter_washer_idiameter_alter_washer_odiameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washer',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BoltMan.bolt_material', verbose_name='Part material'),
        ),
    ]
