# Generated by Django 4.2.14 on 2024-08-27 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoltMan', '0005_alter_washer_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolt_geometry',
            name='head_height',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Head height:'),
        ),
        migrations.AlterField(
            model_name='bolt_geometry',
            name='headdiameter',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Head dieamter:'),
        ),
        migrations.AlterField(
            model_name='bolt_geometry',
            name='norm',
            field=models.CharField(blank=True, default='Not defined', max_length=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bolt_geometry',
            name='shank_length',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Shank length:'),
        ),
        migrations.AlterField(
            model_name='bolt_geometry',
            name='thread_size',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Thread size:'),
        ),
        migrations.AlterField(
            model_name='bolt_geometry',
            name='total_length',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total length:'),
        ),
    ]
