# Generated by Django 4.2.14 on 2024-08-28 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoltMan', '0006_alter_bolt_geometry_head_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolt_geometry',
            name='tsa',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tensile Stress Area (mm^2)'),
        ),
        migrations.AlterField(
            model_name='friction_thread',
            name='f_class',
            field=models.CharField(choices=[('CLASS_A', 'Class A'), ('CLASS_B', 'Class B'), ('CLASS_C', 'Class C'), ('CLASS_D', 'Class D'), ('CLASS_E', 'Class E'), ('SC1', 'SC1'), ('SC2', 'SC2'), ('SC3', 'SC3'), ('SC4', 'SC4'), ('SC5', 'SC5'), ('SC6', 'SC6'), ('SC7', 'SC7'), ('SC8', 'SC8'), ('BC1', 'BC1'), ('BC2', 'BC2'), ('BC3', 'BC3'), ('BC4', 'BC4'), ('BC5', 'BC5'), ('NC', 'Not Classified')], default=None, max_length=100, verbose_name='Class'),
        ),
    ]
