# Generated by Django 4.2.14 on 2024-08-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoltMan', '0007_alter_bolt_geometry_tsa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolt_case',
            name='part1',
        ),
        migrations.RemoveField(
            model_name='bolt_case',
            name='part2',
        ),
        migrations.RemoveField(
            model_name='bolt_case',
            name='part3',
        ),
    ]
