# Generated by Django 4.2.14 on 2024-08-30 11:41

import EcoMan.scripts.colors
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0025_alter_analysis_settings_is_automotive_and_more'),
        ('ConceptMan', '0002_alter_concept_project_model'),
        ('BoltMan', '0008_remove_bolt_case_part1_remove_bolt_case_part2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolted_Part',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(blank=True, default='Not defined', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(default=EcoMan.scripts.colors.get_random_color, max_length=7)),
                ('notes', models.CharField(blank=True, default='Not defined', max_length=600)),
                ('thickness', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Thread size:')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BoltMan.bolt_material')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EcoMan.projectuser_ecoman_ref')),
                ('part_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ConceptMan.part')),
                ('project_model', models.ForeignKey(blank=True, default=None, help_text='Select a project for part', null=True, on_delete=django.db.models.deletion.CASCADE, to='EcoMan.project_ecoman_ref', verbose_name='Project')),
            ],
        ),
        migrations.AddField(
            model_name='bolt_case',
            name='part1',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_part1', to='BoltMan.bolted_part'),
        ),
        migrations.AddField(
            model_name='bolt_case',
            name='part2',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_part2', to='BoltMan.bolted_part'),
        ),
        migrations.AddField(
            model_name='bolt_case',
            name='part3',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a part', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_part3', to='BoltMan.bolted_part'),
        ),
    ]
