# Generated by Django 4.2.14 on 2024-08-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoltMan', '0009_bolted_part_bolt_case_part1_bolt_case_part2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolted_part',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
    ]
