# Generated by Django 4.2.14 on 2024-08-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoltMan', '0011_alter_bolted_part_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bolt_case',
            old_name='part1',
            new_name='part_1',
        ),
        migrations.RenameField(
            model_name='bolt_case',
            old_name='part2',
            new_name='part_2',
        ),
        migrations.RenameField(
            model_name='bolt_case',
            old_name='part3',
            new_name='part_3',
        ),
    ]
