# Generated by Django 4.2.7 on 2023-11-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ConceptMan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='project_model',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a a project for analysis', null=True, on_delete=django.db.models.deletion.CASCADE, to='ConceptMan.project_conceptman_ref', verbose_name='Project'),
        ),
    ]
