# Generated by Django 4.2.7 on 2024-01-19 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DotNet_Component',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, verbose_name='Job will be visible for other colleagues within the same project')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Part Image')),
                ('gif', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Part Image')),
                ('type', models.CharField(choices=[('DOTNET_CLASS', '.net class'), ('DOTNET_METHOD', '.net method')], default='private', max_length=50)),
                ('accessibility', models.CharField(choices=[('PRIVATE', 'Private'), ('DATABASE_USERS', 'Database Users'), ('PROJECT_USERS', 'Project Users')], default='private', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project_CatiaFramework_Ref',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser_CatiaFramework_Ref',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('nickname', models.CharField(blank=True, default='Not defined', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DotNet_Module',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, verbose_name='Job will be visible for other colleagues within the same project')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Part Image')),
                ('gif', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Part Image')),
                ('group_depth_level', models.IntegerField(default=0)),
                ('accessibility', models.CharField(choices=[('PRIVATE', 'Private'), ('DATABASE_USERS', 'Database Users'), ('PROJECT_USERS', 'Project Users')], default='PRIVATE', max_length=50)),
                ('dotnet_components', models.ManyToManyField(blank=True, to='CatiaFramework.dotnet_component', verbose_name='.Net Components')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CatiaFramework.projectuser_catiaframework_ref')),
                ('parent_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.dotnet_module', verbose_name='Parent Modeule')),
                ('project_model', models.ForeignKey(blank=True, default=None, help_text='Select a a project for Shared Component', on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.project_catiaframework_ref', verbose_name='Project')),
            ],
        ),
        migrations.AddField(
            model_name='dotnet_component',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CatiaFramework.projectuser_catiaframework_ref'),
        ),
        migrations.AddField(
            model_name='dotnet_component',
            name='project_model',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a a project for Shared Component', on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.project_catiaframework_ref', verbose_name='Project'),
        ),
    ]
