# Generated by Django 4.2.7 on 2024-01-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0002_rename_parent_group_dotnet_module_parent_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotnet_module',
            name='project_model',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a a project for Shared Component', null=True, on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.project_catiaframework_ref', verbose_name='Project'),
        ),
    ]
