# Generated by Django 4.2.7 on 2024-01-19 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0003_alter_dotnet_module_project_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotNet_Object',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, verbose_name='Job will be visible for other colleagues within the same project')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Part Image')),
                ('gif', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Part Image')),
                ('accessibility', models.CharField(choices=[('PRIVATE', 'Private'), ('DATABASE_USERS', 'Database Users'), ('PROJECT_USERS', 'Project Users')], default='private', max_length=50)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CatiaFramework.projectuser_catiaframework_ref')),
                ('project_model', models.ForeignKey(blank=True, default=None, help_text='Select a a project for Shared Component', on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.project_catiaframework_ref', verbose_name='Project')),
            ],
        ),
    ]
