# Generated by Django 4.2.7 on 2024-01-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0004_dotnet_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DotNet_Module',
            new_name='DotNet_ProjectFolder',
        ),
        migrations.AddField(
            model_name='dotnet_component',
            name='access_modifier',
            field=models.CharField(choices=[('PUBLIC', 'vb.net Public'), ('PRIVATE', 'vb.net Private'), ('PROTECTED', 'vb.net sub Protected'), ('FRIEND', 'vb.net Friend'), ('PROTECTED', 'vb.net Protected')], default='private', max_length=50),
        ),
        migrations.AddField(
            model_name='dotnet_component',
            name='comment_section',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='dotnet_component',
            name='comment_tags',
            field=models.JSONField(blank=True, null=True, verbose_name='workflow_status'),
        ),
        migrations.AddField(
            model_name='dotnet_component',
            name='content_section',
            field=models.CharField(blank=True, max_length=3000000, null=True),
        ),
        migrations.AlterField(
            model_name='dotnet_component',
            name='type',
            field=models.CharField(choices=[('VBDOTNET_CLASS', 'vb.net class'), ('VBDOTNET_MODULE', 'vb.net module'), ('VBDOTNET_SUB', 'vb.net sub procedure'), ('VBDOTNET_FUNCTION', 'vb.net function'), ('VBDOTNET_PROPERTY', 'vb.net property')], default='private', max_length=50),
        ),
        migrations.DeleteModel(
            name='DotNet_Object',
        ),
    ]
