# Generated by Django 4.2.7 on 2024-01-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0005_rename_dotnet_module_dotnet_projectfolder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotnet_component',
            name='access_modifier',
            field=models.CharField(choices=[('PUBLIC', 'vb.net Public'), ('PRIVATE', 'vb.net Private'), ('PROTECTED', 'vb.net sub Protected'), ('FRIEND', 'vb.net Friend'), ('PROTECTED', 'vb.net Protected'), ('NONE', 'None')], default='private', max_length=50),
        ),
        migrations.AlterField(
            model_name='dotnet_component',
            name='type',
            field=models.CharField(choices=[('VBDOTNET_CLASS', 'vb.net class'), ('VBDOTNET_MODULE', 'vb.net module'), ('VBDOTNET_SUB', 'vb.net sub procedure'), ('VBDOTNET_FUNCTION', 'vb.net function'), ('VBDOTNET_PROPERTY', 'vb.net property'), ('DJANGO_VIEW', 'Django view')], default='private', max_length=50),
        ),
    ]
