# Generated by Django 4.2.7 on 2024-01-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0006_alter_dotnet_component_access_modifier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dotnet_projectfolder',
            old_name='parent_module',
            new_name='parent_folder',
        ),
    ]
