# Generated by Django 4.2.7 on 2024-01-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0007_rename_parent_module_dotnet_projectfolder_parent_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotnet_component',
            name='comment_tags',
        ),
        migrations.AddField(
            model_name='dotnet_component',
            name='content_summary',
            field=models.CharField(blank=True, max_length=3000000, null=True),
        ),
    ]
