# Generated by Django 4.2.7 on 2024-01-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0010_workflow_action_workflow_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='shared_component',
        ),
    ]
