# Generated by Django 4.2.7 on 2024-01-29 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0011_remove_workflow_shared_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='reference_workflow',
            field=models.ForeignKey(blank=True, default=None, help_text='Reference Definition Workflow', on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.workflow', verbose_name='Reference Workflow'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='reference_workflow_version',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
