# Generated by Django 4.2.7 on 2024-01-29 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0012_workflow_reference_workflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='reference_workflow',
            field=models.ForeignKey(blank=True, default=None, help_text='Reference Definition Workflow', null=True, on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.workflow', verbose_name='Reference Workflow'),
        ),
    ]
