# Generated by Django 4.2.7 on 2024-01-29 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0013_alter_workflow_reference_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='project_model',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a a project for Shared Component', null=True, on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.project_catiaframework_ref', verbose_name='Project'),
        ),
    ]
