# Generated by Django 4.2.7 on 2024-01-29 13:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0014_alter_workflow_project_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_action',
            name='automatic_trigger',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Trigger Action UUID'),
        ),
        migrations.AlterField(
            model_name='workflow_stage',
            name='parent_stage',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Dependent Session', null=True, on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.workflow_stage', verbose_name='Parent Stage'),
        ),
    ]
