# Generated by Django 4.2.7 on 2024-01-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0015_alter_workflow_action_automatic_trigger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_stage',
            name='project_model',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a a project for Shared Component', null=True, on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.project_catiaframework_ref', verbose_name='Project'),
        ),
    ]
