# Generated by Django 4.2.7 on 2024-01-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0016_alter_workflow_stage_project_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_stage',
            name='parent_stage',
        ),
    ]
