# Generated by Django 4.2.7 on 2024-01-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0017_remove_workflow_stage_parent_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_stage',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='workflow_stage',
            name='objects',
        ),
    ]
