# Generated by Django 4.2.7 on 2024-01-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0019_workflow_stage_parent_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_stage',
            name='objects',
            field=models.ManyToManyField(blank=True, to='CatiaFramework.workflow_object', verbose_name='Created Objects'),
        ),
    ]
