# Generated by Django 4.2.7 on 2024-01-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0021_workflow_stage_actions_alter_workflow_stage_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_stage',
            name='actions',
            field=models.ManyToManyField(blank=True, default=None, to='CatiaFramework.workflow_action', verbose_name='Actions'),
        ),
        migrations.AlterField(
            model_name='workflow_stage',
            name='objects',
            field=models.ManyToManyField(blank=True, default=None, to='CatiaFramework.workflow_object', verbose_name='Created Objects'),
        ),
    ]
