# Generated by Django 4.2.7 on 2024-01-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0022_alter_workflow_stage_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_stage',
            name='actions',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_Stage_Actions', to='CatiaFramework.workflow_action', verbose_name='Actions'),
        ),
        migrations.AlterField(
            model_name='workflow_stage',
            name='objects',
            field=models.ManyToManyField(blank=True, default=None, related_name='%(class)s_Stage_Objects', to='CatiaFramework.workflow_object', verbose_name='Created Objects'),
        ),
    ]
