# Generated by Django 4.2.7 on 2024-01-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0025_alter_workflow_object_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_object',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_Object_Actions', to='CatiaFramework.workflow_action', verbose_name='Actions'),
        ),
    ]
