# Generated by Django 4.2.7 on 2024-01-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0026_alter_workflow_object_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_stage',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='workflow_stage',
            name='objects',
        ),
        migrations.AddField(
            model_name='workflow_stage',
            name='stage_actions',
            field=models.ManyToManyField(blank=True, default=None, to='CatiaFramework.workflow_action', verbose_name='Actions'),
        ),
        migrations.AddField(
            model_name='workflow_stage',
            name='stage_objects',
            field=models.ManyToManyField(blank=True, default=None, to='CatiaFramework.workflow_object', verbose_name='Created Objects'),
        ),
    ]
