# Generated by Django 4.2.7 on 2024-01-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0027_remove_workflow_stage_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_action',
            name='automatic_trigger',
            field=models.UUIDField(blank=True, null=True, verbose_name='Trigger Action UUID'),
        ),
    ]
