# Generated by Django 4.2.7 on 2024-01-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0031_alter_workflow_action_instruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='instruction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.workflow_instruction', verbose_name='Instruction'),
        ),
        migrations.AlterField(
            model_name='workflow_action',
            name='instruction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.workflow_instruction', verbose_name='Instruction'),
        ),
        migrations.AlterField(
            model_name='workflow_object',
            name='instruction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.workflow_instruction', verbose_name='Instruction'),
        ),
        migrations.AlterField(
            model_name='workflow_stage',
            name='instruction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.workflow_instruction', verbose_name='Instruction'),
        ),
    ]
