# Generated by Django 4.2.7 on 2024-01-30 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0032_alter_workflow_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_object',
            name='parent_stage',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Dependent Session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CatiaFramework.workflow_object', verbose_name='Parent Object'),
        ),
    ]
