# Generated by Django 4.2.7 on 2024-01-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0033_workflow_object_parent_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_object',
            name='parent_stage',
        ),
    ]
