# Generated by Django 4.2.7 on 2024-01-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0034_remove_workflow_object_parent_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_object',
            name='instances',
            field=models.ManyToManyField(blank=True, to='CatiaFramework.workflow_object', verbose_name='Instances'),
        ),
        migrations.AlterField(
            model_name='workflow_object',
            name='type',
            field=models.CharField(choices=[('TEMPLATE', 'Template'), ('INSTANCE', 'Instance')], max_length=50),
        ),
    ]
