# Generated by Django 4.2.7 on 2024-01-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0035_workflow_object_instances_alter_workflow_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_stage',
            name='type',
            field=models.CharField(choices=[('UNDEFINED', 'Undefined'), ('STAGE', 'Stage'), ('STEP', 'Step')], default='STAGE', max_length=50),
        ),
    ]
