# Generated by Django 4.2.7 on 2024-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0036_alter_workflow_stage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_stage',
            name='type',
            field=models.CharField(choices=[('UNDEFINED', 'Undefined'), ('STAGE', 'Stage'), ('STEP', 'Step'), ('PROCESS', 'Process')], default='STAGE', max_length=50),
        ),
    ]
