# Generated by Django 4.2.7 on 2024-01-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0037_alter_workflow_stage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_object',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Object instance is used from other references'),
        ),
    ]
