# Generated by Django 4.2.7 on 2024-01-31 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0039_remove_workflow_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_stage',
            name='parent_workflow',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Worf', null=True, on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.workflow', verbose_name='Parent Workflow'),
        ),
    ]
