# Generated by Django 4.2.7 on 2024-02-01 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0040_workflow_stage_parent_workflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_action',
            name='comment_section',
        ),
        migrations.RemoveField(
            model_name='workflow_action',
            name='content_section',
        ),
        migrations.RemoveField(
            model_name='workflow_action',
            name='summary_section',
        ),
        migrations.RemoveField(
            model_name='workflow_stage',
            name='stage_actions',
        ),
        migrations.RemoveField(
            model_name='workflow_stage',
            name='stage_objects',
        ),
        migrations.AddField(
            model_name='workflow_action',
            name='parent_action',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Object_Parent', to='CatiaFramework.workflow_action', verbose_name='Parent Action'),
        ),
        migrations.AddField(
            model_name='workflow_action',
            name='parent_stage',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Dependent Session', null=True, on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.workflow_stage', verbose_name='Parent Stage'),
        ),
        migrations.AddField(
            model_name='workflow_action',
            name='required_actions',
            field=models.ManyToManyField(blank=True, default=None, to='CatiaFramework.workflow_action', verbose_name='Parent Actions'),
        ),
        migrations.AddField(
            model_name='workflow_action',
            name='required_objects',
            field=models.ManyToManyField(blank=True, default=None, to='CatiaFramework.workflow_object', verbose_name='Parent Objects'),
        ),
        migrations.AddField(
            model_name='workflow_object',
            name='parent_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Object_Parent', to='CatiaFramework.workflow_action', verbose_name='Parent Action'),
        ),
        migrations.AddField(
            model_name='workflow_object',
            name='parent_stage',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Dependent Session', null=True, on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.workflow_stage', verbose_name='Parent Stage'),
        ),
        migrations.AddField(
            model_name='workflow_object',
            name='required_actions',
            field=models.ManyToManyField(blank=True, default=None, to='CatiaFramework.workflow_action', verbose_name='Required Actions'),
        ),
        migrations.AddField(
            model_name='workflow_object',
            name='required_objects',
            field=models.ManyToManyField(blank=True, default=None, to='CatiaFramework.workflow_object', verbose_name='Parent Objects'),
        ),
        migrations.AlterField(
            model_name='workflow_object',
            name='instances',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_Object_Instances', to='CatiaFramework.workflow_object', verbose_name='Instances'),
        ),
        migrations.AlterField(
            model_name='workflow_object',
            name='status',
            field=models.CharField(choices=[('DECLARED', 'Declared'), ('IN_PROGRESS', 'In Progress'), ('IS_DONE', 'Done'), ('FAILED', 'Failed'), ('UNDEFINED', 'Undefined')], default='UNDEFINED', max_length=50),
        ),
    ]
