# Generated by Django 4.2.7 on 2024-02-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0042_workflow_action_parent_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_object',
            name='parent_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_Object_Parent', to='CatiaFramework.workflow_object', verbose_name='Parent Action'),
        ),
    ]
