# Generated by Django 4.2.7 on 2024-02-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0044_alter_workflow_object_parent_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_action',
            name='required_actions',
            field=models.ManyToManyField(blank=True, default=None, to='CatiaFramework.workflow_action', verbose_name='Required Actions'),
        ),
        migrations.AlterField(
            model_name='workflow_action',
            name='required_objects',
            field=models.ManyToManyField(blank=True, default=None, to='CatiaFramework.workflow_object', verbose_name='Required Objects'),
        ),
    ]
