# Generated by Django 4.2.7 on 2024-02-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0046_alter_workflow_status_alter_workflow_action_gif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_action',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Action can be called'),
        ),
        migrations.AlterField(
            model_name='workflow_instruction',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Instruction Image/Animation'),
        ),
        migrations.AlterField(
            model_name='workflow_object',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Animated Thumbnail'),
        ),
        migrations.AlterField(
            model_name='workflow_object',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Thumbnail'),
        ),
    ]
