# Generated by Django 4.2.7 on 2024-02-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0047_alter_workflow_action_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancellec'), ('INPROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('UNKNOWN', 'Unknown'), ('WAITING', 'Waiting'), ('FAILED', 'Failed')], default='UNDEFINED', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow_action',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancellec'), ('INPROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('UNKNOWN', 'Unknown'), ('WAITING', 'Waiting'), ('FAILED', 'Failed')], default='UNDEFINED', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow_object',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancellec'), ('INPROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('UNKNOWN', 'Unknown'), ('WAITING', 'Waiting'), ('FAILED', 'Failed')], default='UNDEFINED', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow_stage',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancellec'), ('INPROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('UNKNOWN', 'Unknown'), ('WAITING', 'Waiting'), ('FAILED', 'Failed')], default='UNDEFINED', max_length=50),
        ),
    ]
