# Generated by Django 4.2.7 on 2024-02-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0048_alter_workflow_status_alter_workflow_action_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_action',
            name='parent_action',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_children_action', to='CatiaFramework.workflow_action', verbose_name='Parent Action'),
        ),
        migrations.AlterField(
            model_name='workflow_action',
            name='parent_object',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Dependent Object', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_children_object', to='CatiaFramework.workflow_object', verbose_name='Parent Object'),
        ),
        migrations.AlterField(
            model_name='workflow_action',
            name='parent_stage',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Dependent Session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions_children_stage', to='CatiaFramework.workflow_stage', verbose_name='Parent Stage'),
        ),
        migrations.AlterField(
            model_name='workflow_action',
            name='type',
            field=models.CharField(choices=[('SESSION', 'Session'), ('TEMPLATE', 'Template'), ('FRAMEWORK_INTERNAL', 'Framework Internal')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow_object',
            name='parent_object',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_children_object', to='CatiaFramework.workflow_object', verbose_name='Parent Object'),
        ),
        migrations.AlterField(
            model_name='workflow_object',
            name='parent_stage',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Dependent Session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_children_stage', to='CatiaFramework.workflow_stage', verbose_name='Parent Stage'),
        ),
        migrations.AlterField(
            model_name='workflow_object',
            name='type',
            field=models.CharField(choices=[('SESSION', 'Session'), ('TEMPLATE', 'Template'), ('FRAMEWORK_INTERNAL', 'Framework Internal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow_stage',
            name='parent_stage',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Dependent Session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages_children_stage', to='CatiaFramework.workflow_stage', verbose_name='Parent Stage'),
        ),
        migrations.AlterField(
            model_name='workflow_stage',
            name='parent_workflow',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Worf', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages_children_workflow', to='CatiaFramework.workflow', verbose_name='Parent Workflow'),
        ),
        migrations.AlterField(
            model_name='workflow_stage',
            name='type',
            field=models.CharField(choices=[('SESSION', 'Session'), ('TEMPLATE', 'Template'), ('FRAMEWORK_INTERNAL', 'Framework Internal')], default='STAGE', max_length=50),
        ),
    ]
