# Generated by Django 4.2.7 on 2024-02-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0049_alter_workflow_action_parent_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_stage',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active For User Interaction'),
        ),
    ]
