# Generated by Django 4.2.7 on 2024-02-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0050_alter_workflow_stage_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_action',
            name='access_modifier',
        ),
        migrations.RemoveField(
            model_name='workflow_action',
            name='gif',
        ),
    ]
