# Generated by Django 4.2.7 on 2024-02-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0051_remove_workflow_action_access_modifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_object',
            name='actions',
        ),
    ]
