# Generated by Django 4.2.7 on 2024-02-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0053_workflow_object_is_interactive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_object',
            name='gif',
        ),
        migrations.RemoveField(
            model_name='workflow_object',
            name='type',
        ),
        migrations.AlterField(
            model_name='workflow_action',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Object is activated'),
        ),
    ]
