# Generated by Django 4.2.7 on 2024-02-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0054_remove_workflow_object_gif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_action',
            name='parent_action',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_children_action', to='CatiaFramework.workflow_action', verbose_name='Parent Action'),
        ),
    ]
