# Generated by Django 4.2.7 on 2024-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0055_alter_workflow_action_parent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_action',
            name='accessibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('DATABASE_USERS', 'Database Users'), ('PROJECT_USERS', 'Project Users')], default='PRIVATE', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow_action',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancellec'), ('INPROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('UNKNOWN', 'Unknown'), ('WAITING', 'Waiting'), ('FAILED', 'Failed')], default='WAITING', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow_action',
            name='type',
            field=models.CharField(choices=[('SESSION', 'Session'), ('TEMPLATE', 'Template'), ('FRAMEWORK_INTERNAL', 'Framework Internal')], default='SESSION', max_length=50),
        ),
    ]
