# Generated by Django 4.2.10 on 2024-02-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0056_alter_workflow_action_accessibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Workflow will be visible for other colleagues within the same project'),
        ),
    ]
