# Generated by Django 4.2.10 on 2024-02-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0057_alter_workflow_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='gif',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Thumbnail'),
        ),
    ]
