# Generated by Django 4.2.10 on 2024-02-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0058_remove_workflow_gif_alter_workflow_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_object',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=50000, null=True, upload_to='uploads/', verbose_name='Thumbnail'),
        ),
    ]
