# Generated by Django 4.0.6 on 2024-02-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0059_alter_workflow_object_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_object',
            name='instance_properties',
            field=models.JSONField(blank=True, null=True, verbose_name='Instance Properties'),
        ),
    ]
