# Generated by Django 4.2.10 on 2024-03-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0061_workflow_object_instance_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_object',
            name='instance_properties',
        ),
    ]
