# Generated by Django 4.2.10 on 2024-03-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0062_remove_workflow_object_instance_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_object',
            name='instance_framework_metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Instance Framework Metadata'),
        ),
    ]
