# Generated by Django 4.2.10 on 2024-03-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0063_workflow_object_instance_framework_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_object',
            name='instances',
            field=models.ManyToManyField(blank=True, related_name='objects_instances', to='CatiaFramework.workflow_object', verbose_name='Instances'),
        ),
    ]
