# Generated by Django 4.2.10 on 2024-03-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0064_alter_workflow_object_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_object',
            name='type',
            field=models.CharField(choices=[('INSTANCE', 'Instance'), ('TEMPLATE', 'Template'), ('FRAMEWORK_INTERNAL', 'Framework Internal')], default='STAGE', max_length=50),
        ),
    ]
