# Generated by Django 4.2.10 on 2024-03-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0067_alter_workflow_object_parent_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_stage',
            name='parent_stage',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Dependent Session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages_children_stages', to='CatiaFramework.workflow_stage', verbose_name='Parent Stage'),
        ),
        migrations.AlterField(
            model_name='workflow_stage',
            name='parent_workflow',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Worf', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows_children_stages', to='CatiaFramework.workflow', verbose_name='Parent Workflow'),
        ),
    ]
