# Generated by Django 4.2.10 on 2024-03-06 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0068_alter_workflow_stage_parent_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_action',
            name='parent_action',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_children_actions', to='CatiaFramework.workflow_action', verbose_name='Parent Action'),
        ),
        migrations.AlterField(
            model_name='workflow_action',
            name='parent_object',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Dependent Object', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_children_actions', to='CatiaFramework.workflow_object', verbose_name='Parent Object'),
        ),
        migrations.AlterField(
            model_name='workflow_action',
            name='parent_stage',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Dependent Session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages_children_actions', to='CatiaFramework.workflow_stage', verbose_name='Parent Stage'),
        ),
    ]
