# Generated by Django 4.2.10 on 2024-03-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0069_alter_workflow_action_parent_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_action',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('INPROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('UNKNOWN', 'Unknown'), ('WAITING', 'Waiting'), ('FAILED', 'Failed'), ('CAUTION', 'Caution')], default='WAITING', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow_object',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('INPROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('UNKNOWN', 'Unknown'), ('WAITING', 'Waiting'), ('FAILED', 'Failed'), ('CAUTION', 'Caution')], default='UNDEFINED', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow_stage',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('INPROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('UNKNOWN', 'Unknown'), ('WAITING', 'Waiting'), ('FAILED', 'Failed'), ('CAUTION', 'Caution')], default='UNDEFINED', max_length=50),
        ),
    ]
