# Generated by Django 4.2.10 on 2024-04-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0070_alter_workflow_action_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_action',
            name='target_object',
            field=models.ForeignKey(blank=True, default=None, help_text='Parent Dependent Object', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_trigger_actions', to='CatiaFramework.workflow_object', verbose_name='Target Object'),
        ),
    ]
