# Generated by Django 4.2.10 on 2024-04-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0071_workflow_action_target_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_object',
            name='UUID',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
