# Generated by Django 4.2.10 on 2024-04-30 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0072_alter_workflow_object_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow_Session',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Thumbnail')),
                ('gif', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Animated Thumbnail')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('INPROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('UNKNOWN', 'Unknown'), ('WAITING', 'Waiting'), ('FAILED', 'Failed'), ('CAUTION', 'Caution')], default='UNDEFINED', max_length=50)),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active For User Interaction')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CatiaFramework.projectuser_catiaframework_ref')),
                ('project_model', models.ForeignKey(blank=True, default=None, help_text='Select a a project for Shared Component', null=True, on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.project_catiaframework_ref', verbose_name='Project')),
                ('workflow_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='workflowss_reference_sessions', to='CatiaFramework.workflow', verbose_name='Workflow Template of this Sesion')),
            ],
        ),
    ]
