# Generated by Django 4.2.10 on 2024-04-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0073_workflow_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_object',
            name='workflow_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_object_instances', to='CatiaFramework.workflow_session', verbose_name='Workflow Session'),
        ),
    ]
