# Generated by Django 4.2.10 on 2024-05-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0074_workflow_object_workflow_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_action',
            name='is_for_all_instances',
            field=models.UUIDField(blank=True, null=True, verbose_name='Execute on all required instances'),
        ),
    ]
