# Generated by Django 4.2.10 on 2024-05-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0075_workflow_action_is_for_all_instances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_action',
            name='is_for_all_instances',
        ),
    ]
