# Generated by Django 4.2.10 on 2024-05-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0078_workflow_object_reference_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_object',
            name='instances',
            field=models.ManyToManyField(blank=True, related_name='instances_object', to='CatiaFramework.workflow_object', verbose_name='Instances'),
        ),
    ]
