# Generated by Django 4.2.10 on 2024-05-13 13:09

from CatiaFramework.models.Workflow.object import SessionCustomUploadPath
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0079_alter_workflow_object_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_object',
            name='catia_representation',
            field=models.FileField(blank=True, null=True, upload_to=SessionCustomUploadPath, verbose_name='3D Catia representation'),
        ),
        migrations.AddField(
            model_name='workflow_object',
            name='wrl_representation',
            field=models.FileField(blank=True, null=True, upload_to=SessionCustomUploadPath, verbose_name='3D VRML representation'),
        ),
    ]
