# Generated by Django 4.2.10 on 2024-05-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0080_workflow_object_catia_representation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_object',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Thumbnail', max_length=50000),
        ),
    ]
