# Generated by Django 4.2.10 on 2024-05-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0082_workflow_object_norman_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='static_structure',
            field=models.JSONField(blank=True, null=True, verbose_name='Workflow Structure'),
        ),
    ]
