# Generated by Django 4.2.10 on 2024-05-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0083_workflow_static_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_action',
            name='status',
        ),
        migrations.AddField(
            model_name='workflow_session',
            name='session_metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Session Metadata'),
        ),
    ]
