# Generated by Django 4.0.6 on 2024-05-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0084_remove_workflow_action_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_session',
            name='session_metadata',
            field=models.JSONField(default=dict, verbose_name='Session Metadata'),
        ),
    ]
