# Generated by Django 4.2.10 on 2024-06-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0085_alter_workflow_session_session_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='modified',
            field=models.BooleanField(default=False, verbose_name='Status flag indicating the need to update the static structure'),
        ),
    ]
