# Generated by Django 4.2.10 on 2024-06-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0087_workflow_session_protection_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_action',
            name='automatic_trigger',
        ),
        migrations.AddField(
            model_name='workflow_action',
            name='auverride_parameters',
            field=models.BooleanField(default=False, verbose_name='User Custom Parameters on Execution'),
        ),
    ]
