# Generated by Django 4.0.6 on 2024-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0089_workflow_action_url_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_object',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Thumbnail'),
        ),
    ]
