# Generated by Django 4.2.14 on 2024-09-10 08:39

import CatiaFramework.models.dotnet_library
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NormMan', '0003_alter_workflow_session_created_objects'),
        ('CatiaFramework', '0090_alter_workflow_object_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dotnet_Library',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('data_path', models.CharField(blank=True, max_length=50000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_file', models.FileField(blank=True, null=True, upload_to=CatiaFramework.models.dotnet_library.library_file_path)),
                ('meta', models.FileField(blank=True, null=True, upload_to=CatiaFramework.models.dotnet_library.meta_file_path)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=CatiaFramework.models.dotnet_library.thumbnail_file_path)),
                ('source', models.CharField(blank=True, max_length=1000)),
                ('is_token_required', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='NormMan.projectuser_normman_ref')),
                ('project_model', models.ForeignKey(blank=True, default=None, help_text='Select a a project for Shared Component', on_delete=django.db.models.deletion.CASCADE, to='NormMan.project_normman_ref', verbose_name='Project')),
            ],
        ),
    ]
