# Generated by Django 4.2.14 on 2024-09-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0091_dotnet_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotnet_projectfolder',
            name='dotnet_libraries',
            field=models.ManyToManyField(blank=True, to='CatiaFramework.dotnet_library', verbose_name='.Net Libraries'),
        ),
    ]
