# Generated by Django 4.2.14 on 2024-09-10 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NormMan', '0003_alter_workflow_session_created_objects'),
        ('CatiaFramework', '0092_dotnet_projectfolder_dotnet_libraries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotnet_projectfolder',
            name='project_model',
        ),
        migrations.AlterField(
            model_name='dotnet_library',
            name='project_model',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a project for Shared Component', on_delete=django.db.models.deletion.CASCADE, to='NormMan.project_normman_ref', verbose_name='Project'),
        ),
    ]
