# Generated by Django 4.2.14 on 2024-09-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0093_remove_dotnet_projectfolder_project_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotnet_projectfolder',
            name='project_model',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a a project for Shared Component', null=True, on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.project_catiaframework_ref', verbose_name='Project'),
        ),
    ]
