# Generated by Django 4.2.14 on 2024-09-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0094_dotnet_projectfolder_project_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotnet_projectfolder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CatiaFramework.dotnet_projectfolder', verbose_name='Parent Modeule'),
        ),
    ]
