# Generated by Django 4.2.14 on 2024-09-10 10:51

import CatiaFramework.models.dotnet_component
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0095_alter_dotnet_projectfolder_parent_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotnet_component',
            name='gif',
        ),
        migrations.AddField(
            model_name='dotnet_component',
            name='library_file',
            field=models.FileField(blank=True, null=True, upload_to=CatiaFramework.models.dotnet_component.library_file_path),
        ),
        migrations.AddField(
            model_name='dotnet_component',
            name='meta',
            field=models.FileField(blank=True, null=True, upload_to=CatiaFramework.models.dotnet_component.meta_file_path),
        ),
        migrations.AlterField(
            model_name='dotnet_component',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=CatiaFramework.models.dotnet_component.thumbnail_file_path),
        ),
        migrations.AlterField(
            model_name='dotnet_component',
            name='type',
            field=models.CharField(choices=[('VBDOTNET_CLASS', 'vb.net class'), ('VBDOTNET_LIBRARY', 'vb.net library'), ('VBDOTNET_MODULE', 'vb.net module'), ('VBDOTNET_SUB', 'vb.net sub procedure'), ('VBDOTNET_FUNCTION', 'vb.net function'), ('VBDOTNET_PROPERTY', 'vb.net property'), ('DJANGO_VIEW', 'Django view'), ('UNDEFINED', 'Undefined')], default='UNDEFINED', max_length=50),
        ),
    ]
