# Generated by Django 4.2.14 on 2024-09-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatiaFramework', '0096_remove_dotnet_component_gif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotnet_projectfolder',
            name='dotnet_libraries',
        ),
    ]
