# Generated by Django 4.2.7 on 2023-11-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='project_model',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a a project for analysis', null=True, on_delete=django.db.models.deletion.CASCADE, to='EcoMan.project_ecoman_ref', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='analysis_comparison',
            name='project_model',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a a project for analysis', null=True, on_delete=django.db.models.deletion.CASCADE, to='EcoMan.project_ecoman_ref', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='lca_part',
            name='project_model',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a project for part', null=True, on_delete=django.db.models.deletion.CASCADE, to='EcoMan.project_ecoman_ref', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='lca_support_ticket',
            name='project_model',
            field=models.ForeignKey(blank=True, default=None, help_text='Select a a project for TICKET', null=True, on_delete=django.db.models.deletion.CASCADE, to='EcoMan.project_ecoman_ref', verbose_name='Project'),
        ),
    ]
