# Generated by Django 4.2.7 on 2023-11-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0002_alter_analysis_project_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis_comparison',
            name='emissions_manufacturing_including_reuse',
        ),
    ]
