# Generated by Django 4.2.7 on 2023-11-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0004_lca_database_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lca_database',
            name='accessibility',
            field=models.CharField(choices=[('PROJECT', 'Project Related Release'), ('ORGANISATION', 'Official Organisation Relateted Release'), ('IDEMAT', 'Official Idemat Release')], default='PROJECT', max_length=32),
        ),
    ]
