# Generated by Django 4.2.7 on 2023-11-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0005_alter_lca_database_accessibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lca_database',
            name='accessibility',
            field=models.CharField(choices=[('PROJECT', 'Project Related Release'), ('ORGANISATION', 'Official Organisation Relateted Release'), ('OPEN', 'Open Source Release')], default='PROJECT', max_length=32),
        ),
    ]
