# Generated by Django 4.2.7 on 2023-12-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0010_alter_instance_idemat_database_process_results_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance_idemat_database_process',
            name='process_total_quantity',
        ),
    ]
