# Generated by Django 4.2.7 on 2023-12-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0011_remove_instance_idemat_database_process_process_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='protection_class',
        ),
        migrations.RemoveField(
            model_name='analysis_comparison',
            name='protection_class',
        ),
        migrations.AlterField(
            model_name='analysis_settings',
            name='is_playground',
            field=models.BooleanField(default=False, verbose_name='Job will be a comparison comparison not visible as two column'),
        ),
        migrations.AlterField(
            model_name='analysis_settings',
            name='protection_class',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('STRICTLY_CONFIDENTIAL', 'Strictly Confidential')], default='CONFIDENTIAL', max_length=100, verbose_name='Analysis protection class'),
        ),
        migrations.AlterField(
            model_name='lca_database',
            name='accessibility',
            field=models.CharField(choices=[('PROJECT', 'Project Related Release'), ('ORGANISATION', 'Official Organisation Related Release'), ('OPEN', 'Open Source Release')], default='PROJECT', max_length=32),
        ),
    ]
