# Generated by Django 4.2.7 on 2023-12-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0012_remove_analysis_protection_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis_comparison',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Part Image'),
        ),
    ]
