# Generated by Django 4.2.7 on 2024-01-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0015_analysis_utilisation_instance_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lca_database',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Database Image'),
        ),
    ]
