# Generated by Django 4.2.7 on 2024-01-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0016_alter_lca_database_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lca_database',
            name='is_archive',
            field=models.BooleanField(default=True, verbose_name='Database will not be selectable'),
        ),
        migrations.AlterField(
            model_name='lca_database_process',
            name='accessibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('DATABASE_USERS', 'Database Users'), ('HIDDEN', 'Hidden'), ('ARCHIVE', 'Archive')], default='PRIVATE', max_length=50),
        ),
    ]
