# Generated by Django 4.2.7 on 2024-01-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0017_lca_database_is_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lca_database',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Database will not be selectable'),
        ),
    ]
