# Generated by Django 4.2.10 on 2024-07-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0019_alter_lca_database_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis_settings',
            name='weight_units',
            field=models.CharField(choices=[('KILOGRAMS', 'Kilograms [kg]'), ('GRAMS', 'Grams [g]')], default='KILOGRAMS', max_length=32, verbose_name='Weight unit'),
        ),
    ]
