# Generated by Django 4.2.10 on 2024-07-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0021_alter_analysis_settings_is_playground'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis_settings',
            name='is_automotive',
            field=models.BooleanField(default=False, verbose_name='Job functionality tailored as automotive application'),
        ),
    ]
