# Generated by Django 4.2.14 on 2024-08-21 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0023_alter_analysis_settings_is_automotive'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis_settings',
            name='weight_decimal_points',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Decimal Points For Weight'),
        ),
    ]
