# Generated by Django 4.2.14 on 2024-08-29 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMan', '0024_analysis_settings_weight_decimal_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis_settings',
            name='is_automotive',
            field=models.BooleanField(default=False, verbose_name='Job functionality tailored as automotive application'),
        ),
        migrations.AlterField(
            model_name='analysis_settings',
            name='weight_decimal_points',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Decimal Points For Weight'),
        ),
    ]
