# Generated by Django 4.2.7 on 2024-01-09 10:38

from django.db import migrations, models
import django.db.models.deletion
import website.generate_pk


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_project_network_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswordHistory',
            fields=[
                ('id', models.CharField(default=website.generate_pk.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('project_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.projectuser')),
            ],
        ),
    ]
