# Generated by Django 4.0.6 on 2024-02-28 11:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_userpasswordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='keycloak_UUID',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Keycloak User UUID'),
        ),
    ]
