# Generated by Django 4.2.10 on 2024-08-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_projectuser_keycloak_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
