# Generated by Django 4.2.14 on 2024-09-04 06:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_projectuser_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(default='No Name Organisation', max_length=100)),
                ('full_name', models.CharField(default='No Name Organisation GmbH', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Project Image')),
                ('is_current_organisation', models.BooleanField(default=False)),
            ],
        ),
    ]
