# Generated by Django 4.2.14 on 2024-09-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Project Image'),
        ),
    ]
