# Generated by Django 4.2.14 on 2024-09-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_organisation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(default='C:\\Users\\hr63674\\Documents\\BE_PARAMOUNT\\static/website/customer_banner/EDAG_BANNER.png', upload_to='banners/'),
        ),
    ]
