# Generated by Django 4.2.14 on 2024-09-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_organisation_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('token_type', models.CharField(choices=[('limited', 'Limited Usage'), ('unlimited', 'Unlimited Usage'), ('expiry', 'Expiry Date'), ('expiry_limited', 'Expiry and Limited Usage')], default='limited', max_length=20)),
                ('max_usage', models.PositiveIntegerField(blank=True, help_text='Maximum usage count. Leave blank for unlimited.', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this token has been used.')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Expiry date for the token. Leave blank for no expiry.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_component', models.UUIDField(blank=True, default=None, null=True, verbose_name='Shared Component')),
                ('related_tokens', models.ManyToManyField(blank=True, help_text='Tokens that are part of this bundle.', related_name='bundled_tokens', to='website.token')),
            ],
        ),
    ]
