# Generated by Django 4.2.14 on 2024-09-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='tokens',
            field=models.ManyToManyField(blank=True, help_text='Users available tokens', related_name='users_with_token', to='website.token'),
        ),
    ]
