# Generated by Django 4.2.14 on 2024-09-10 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_projectuser_tokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='shared_component',
            new_name='protected_component_UUID',
        ),
    ]
