# Generated by Django 4.2.14 on 2024-09-10 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_shared_component_token_protected_component_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.RemoveField(
            model_name='token',
            name='key',
        ),
        migrations.AddField(
            model_name='token',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
