# Generated by Django 3.0.2 on 2020-10-14 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digilab_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggingentry',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who was logged in when logging entry was created', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
