# Generated by Django 3.0.2 on 2020-10-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digilab_logger', '0002_auto_20201014_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingentry',
            name='log_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loggingentry',
            name='traceback',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
