# Generated by Django 3.0.5 on 2020-11-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digilab_logger', '0004_statuslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggingEntry',
        ),
    ]
