# Generated by Django 4.2.7 on 2023-11-21 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid
import website.generate_pk


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_MatMan_Ref',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser_MatMan_Ref',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('nickname', models.CharField(blank=True, default='Not defined', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_MatMan_Ref',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
            ],
        ),
        migrations.CreateModel(
            name='Engineering_Material',
            fields=[
                ('id', models.CharField(default=website.generate_pk.generate_pk, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default='Not defined', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aisi', models.CharField(blank=True, default='Not defined', max_length=20, verbose_name='AISI')),
                ('din', models.CharField(blank=True, default='Not defined', max_length=20, verbose_name='DIN')),
                ('bs', models.CharField(blank=True, default='Not defined', max_length=20, verbose_name='BS')),
                ('af', models.CharField(blank=True, default='Not defined', max_length=20, verbose_name='AF')),
                ('uni', models.CharField(blank=True, default='Not defined', max_length=20, verbose_name='UNI')),
                ('une', models.CharField(blank=True, default='Not defined', max_length=20, verbose_name='UNE')),
                ('jis', models.CharField(blank=True, default='Not defined', max_length=20, verbose_name='JIS')),
                ('csn', models.CharField(blank=True, default='Not defined', max_length=20, verbose_name='CSN')),
                ('name_1', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Name: ')),
                ('name_2', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Alternative Name 1:')),
                ('name_3', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Alternative Name 2:')),
                ('poisonsratio', models.FloatField(verbose_name='Poisons Ratio')),
                ('moeit', models.FloatField(verbose_name='Modulus of elasticity in tension')),
                ('hec', models.FloatField(verbose_name='Heat expansion coeficient')),
                ('density', models.FloatField(verbose_name='Density')),
                ('uts', models.FloatField(verbose_name='Ultimate Tensile Strength, Su(Mpa)')),
                ('ys', models.FloatField(verbose_name='Yield strength, Sy(Mpa)')),
                ('sh', models.FloatField(verbose_name='Shear strength (Mpa)')),
                ('materialgroup', models.CharField(choices=[('Metals Ferrous', 'Metal Ferrous'), ('Metals Non-Ferrous', 'Metal Non-Ferrous'), ('Plastic', 'Plastic'), ('Ceramic', 'Ceramic'), ('Composite', 'Composite'), ('Special', 'Special')], default='Special', max_length=32)),
                ('matcost', models.FloatField(blank=True, default=None, null=True, verbose_name='Material cost per metric ton')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MatMan.projectuser_matman_ref')),
                ('project_model', models.ForeignKey(blank=True, default=None, help_text='Select a a project for analysis', on_delete=django.db.models.deletion.CASCADE, to='MatMan.project_matman_ref', verbose_name='Project')),
            ],
        ),
    ]
