from .shared_component_modal import *
from .dynamic_breadcrumb_modal_view import dynamic_breadcrumb_modal, shared_component_dynamic_breadcrumb_modal
from .workflow_modal import workflow_delete, workflow_update, workflow_create_modal
from .workflow_session_modal import workflow_session_delete, workflow_session_update, workflow_session_create_modal, workflow_session_reset_modal
from .workflow_stage_modal import workflow_stage_create_modal, workflow_stage_update_modal, workflow_stage_delete_modal
from .workflow_object_modal import workflow_object_create_modal, workflow_object_update_modal, workflow_object_delete_modal, workflow_object_delete_all_instances_modal
from .workflow_instruction_modal import workflow_instruction_update_modal
from .workflow_object_instance_modal import workflow_object_instance_create_modal, workflow_object_instance_update_modal, workflow_object_instance_delete_modal, workflow_object_instance_next_tab, workflow_object_select_tab

from .workflow_object_action_modal import workflow_object_action_create_modal, workflow_object_action_update_modal, workflow_object_action_delete_modal, load_content_object_action_create_modal,workflow_object_action_execute_modal
from .workflow_stage_action_modal import workflow_stage_action_create_modal, workflow_stage_action_update_modal, workflow_stage_action_delete_modal, load_content_stage_action_create_modal, workflow_stage_action_execute_modal

from .add_instance_representation_modal import *
from .workflow_object_action_static_add_model import *