# Generated by Django 4.0.6 on 2024-01-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NormMan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_session',
            name='created_objects',
            field=models.JSONField(blank=True, default={}, null=True, verbose_name='created_objects'),
        ),
        migrations.AddField(
            model_name='workflow_session',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Job will be visible for other colleagues within the same project'),
        ),
    ]
