# Generated by Django 4.2.1 on 2024-01-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NormMan', '0002_workflow_session_created_objects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_session',
            name='created_objects',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='created_objects'),
        ),
    ]
